<?php

$lang = [
  "developing" => "【正在做】",
  "currpwd" => "当前密码",
  "email" => "Email",
  "empty-field" => "请填写完整用户信息",
  "fail" => "失败",
  "fail-penalty1" => "密码错误次数过多，请 ",
  "fail-penalty2" => " 秒后重试",
  "hist-back" => "返回上一页",
  "invalid-cred" => "密码错误",
  "invalid-username-1" => "用户名不可用 (含有符号【",
  "invalid-username-2" => "用户名不可用 (含有限制词【",
  "invalid-username-3" => "】)",
  "ip-ban-temp1" => "您的IP已经被禁止，请 ",
  "ip-ban-temp2" => " 小时后重试",
  "logged-out" => "已登出",
  "logged-in" => "已登入",
  "login" => "登入",
  "logout" => "登出",
  "modprofile" => "修改资料",
  "modpwd" => "修改密码",
  "new" => "新",
  "not-logged-in" => "未登入",
  "password" => "密码",
  "password2" => "重复密码",
  "qq" => "QQ",
  "register" => "注册",
  "sitename" => "Un!on-囯阮麿砝帅朕舍仝",
  "status" => "状态",
  "submit" => "提交",
  "success" => "成功",
  "username" => "用户名",
  "username-dup" => "用户名已被注册",
  "username-dne" => "用户名不存在",
];
